services:
  - type: web
    name: drstone-api
    env: node
    buildCommand: npm ci && npm run build
    startCommand: npm start
    healthCheckPath: /api
    envVars:
      - key: NODE_ENV
        value: production